# Codesys binary path
# cod_bin_path = '/home/cd3294/FRIDA/fieldfuzz_frida_tool/old_codesys_binaries/codesyscontrol.bin'
cod_bin_path = '/opt/codesys/bin/codesyscontrol.bin'

# Codesys working directory
# cod_cwd = '/home/cd3294/FRIDA/fieldfuzz_frida_tool/old_codesys_binaries/'
cod_cwd = '/etc/'

# Output file for basic blocks
outfile = 'fieldfuzz-ghost.log'

# Output file for components
cmp_outfile = 'fieldfuzz-ghost-components.log'

# codesyscontrol.bin base address
cod_base_addr = 0x555555554000

# Service handler address (ServerRegisterServiceHandler)
serv_handler_addr = "0x55555DA46E00"

# Unpack delay: time to wait listening for calls to ServerRegisterServiceHandler 
# before starting to intercept components and stalking their threads
unpack_delay = 30

# Components with their ids, servicehandler addresses, and total coverage
component_handlers = {
    0x11c:{
        'name': 'SysEthernet',
        'servicehandler_address': 0x55555da855c0,
        'coverage': 0,
        'covered_instructions': 0,
        'total_instructions': 0
    },
    0x7c:{
        'name': 'CmpAlarmManager',
        'servicehandler_address': 0x55555d5aef00,
        'coverage': 0,
        'covered_instructions': 0,
        'total_instructions': 0
    },
    0x02:{
        'name': 'CmpApp',
        'servicehandler_address': 0x55555d5ca400,
        'coverage': 0,
        'covered_instructions': 0,
        'total_instructions': 0
    },
    0x73:{
        'name': 'CmpAppBP',
        'servicehandler_address': 0x55555d5d0900,
        'coverage': 0,
        'covered_instructions': 0,
        'total_instructions': 0
    },
    0x74:{
        'name': 'CmpAppForce',
        'servicehandler_address': 0x55555d5d2dc0,
        'coverage': 0,
        'covered_instructions': 0,
        'total_instructions': 0
    },
    0x83:{
        'name': 'CmpCoreDump',
        'servicehandler_address': 0x55555d7d3440,
        'coverage': 0,
        'covered_instructions': 0,
        'total_instructions': 0
    },
    0x60:{
        'name': 'CmpIecVarAccess',
        'servicehandler_address': 0x55555d804940,
        'coverage': 0,
        'covered_instructions': 0,
        'total_instructions': 0
    },
    0x12:{
        'name': 'CmpIoMgr',
        'servicehandler_address': 0x55555d80b100,
        'coverage': 0,
        'covered_instructions': 0,
        'total_instructions': 0
    },
    0x32:{
        'name': 'CmpMonitor2',
        'servicehandler_address': 0x55555d823a80,
        'coverage': 0,
        'covered_instructions': 0,
        'total_instructions': 0
    },
    0x128:{
        'name': 'PlcShell',
        'servicehandler_address': 0x55555da28ec0,
        'coverage': 0,
        'covered_instructions': 0,
        'total_instructions': 0
    },
    0x70:{
        'name': 'TraceMgr',
        'servicehandler_address': 0x55555da54f40,
        'coverage': 0,
        'covered_instructions': 0,
        'total_instructions': 0
    },
    0x61:{
        'name': 'CmpUserMgr',
        'servicehandler_address': 0x55555da61bc0,
        'coverage': 0,
        'covered_instructions': 0,
        'total_instructions': 0
    },
    0x57:{
        'name': 'CmpVisuServer',
        'servicehandler_address': 0x55555da71e80,
        'coverage': 0,
        'covered_instructions': 0,
        'total_instructions': 0
    },
    0x5e:{
        'name': 'CmpFileTransfer',
        'servicehandler_address': 0x55555d7e5b00,
        'coverage': 0,
        'covered_instructions': 0,
        'total_instructions': 0
    },
    0x13:{
        'name': 'CmpLog',
        'servicehandler_address': 0x55555d81f7c0,
        'coverage': 0,
        'covered_instructions': 0,
        'total_instructions': 0
    },
    0x1a:{
        'name': 'CmpSettings',
        'servicehandler_address': 0x55555da42700,
        'coverage': 0,
        'covered_instructions': 0,
        'total_instructions': 0
    },
    0x7a:{
        'name': 'CmpCodeMeter',
        'servicehandler_address': 0x55555d764100,
        'coverage': 0,
        'covered_instructions': 0,
        'total_instructions': 0
    },
    0x0e:{
        'name': 'CmpDevice',
        'servicehandler_address': 0x55555d7d7840,
        'coverage': 0,
        'covered_instructions': 0,
        'total_instructions': 0
    },
    0x33:{
        'name': 'CmpOpenSSL',
        'servicehandler_address': 0x55555d8cf6c0,
        'coverage': 0,
        'covered_instructions': 0,
        'total_instructions': 0
    },
}

# Subcomponents
subcomponents = [
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555d7d3440, 0x55555d7d34a3],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpCoreDump_servicehandler.hex',
                     'instruction_indices': []}],
  'name': 'CmpCoreDump:CoreDumpServiceHandler',
  'component_id': 0x83},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555d7d31c0, 0x55555d7d3434],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/cmp_core_dump_cmp_1.hex',
                     'instruction_indices': []}],
  'name': 'CmpCoreDump:cmp_core_dump_cmp_1',
  'component_id': 0x83},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555d7d2e00, 0x55555d7d2fed],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/cmp_core_dump_cmp_2.hex',
                     'instruction_indices': []}],
  'name': 'CmpCoreDump:cmp_core_dump_cmp_2',
  'component_id': 0x83},
 


 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555da54f40, 0x55555da5506b],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpTraceManager_servicehandler.hex',
                     'instruction_indices': []}],
  'name': 'CmpTraceManager:TraceMgrServiceHandler',
  'component_id': 0x70},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555da522c0, 0x55555da523f6],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/tracemgr_packet_read_list.hex',
                     'instruction_indices': []}],
  'name': 'CmpTraceManager:tracemgr_packet_read_list',
  'component_id': 0x70},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555da52400, 0x55555da528b8],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/tracemgr_create_packet.hex',
                     'instruction_indices': []}],
  'name': 'CmpTraceManager:tracemgr_create_packet',
  'component_id': 0x70},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555da528c0, 0x55555da52a08],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/tracemgr_delete_packet.hex',
                     'instruction_indices': []}],
  'name': 'CmpTraceManager:tracemgr_delete_packet',
  'component_id': 0x70},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555da52a40, 0x55555da52b6b],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/tracemgr_complete_packet.hex',
                     'instruction_indices': []}],
  'name': 'CmpTraceManager:tracemgr_complete_packet',
  'component_id': 0x70},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555da52b80, 0x55555da52d55],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/tracemgr_open_packet.hex',
                     'instruction_indices': []}],
  'name': 'CmpTraceManager:tracemgr_open_packet',
  'component_id': 0x70},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555da52d80, 0x55555da52eab],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/tracemgr_open_packet_2.hex',
                     'instruction_indices': []}],
  'name': 'CmpTraceManager:tracemgr_open_packet_2',
  'component_id': 0x70},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555da52ec0, 0x55555da530e1],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/tracemgr_get_status.hex',
                     'instruction_indices': []}],
  'name': 'CmpTraceManager:tracemgr_get_status',
  'component_id': 0x70},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555da53100, 0x55555da537d5],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/tracemgr_read_packet.hex',
                     'instruction_indices': []}],
  'name': 'CmpTraceManager:tracemgr_read_packet',
  'component_id': 0x70},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555da53800, 0x55555da53c70],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/tracemgr_recordgetconfig.hex',
                     'instruction_indices': []}],
  'name': 'CmpTraceManager:tracemgr_recordgetconfig',
  'component_id': 0x70},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555da53c80, 0x55555da53e41],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/tracemgr_get_config.hex',
                     'instruction_indices': []}],
  'name': 'CmpTraceManager:tracemgr_get_config',
  'component_id': 0x70},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555da53e80, 0x55555da53fab],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/tracemgr_start_packet.hex',
                     'instruction_indices': []}],
  'name': 'CmpTraceManager:tracemgr_start_packet',
  'component_id': 0x70},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555da53fc0, 0x55555da540eb],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/tracemgr_stop_packet.hex',
                     'instruction_indices': []}],
  'name': 'CmpTraceManager:tracemgr_stop_packet',
  'component_id': 0x70},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555da54100, 0x55555da5422b],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/tracemgr_restart_packet.hex',
                     'instruction_indices': []}],
  'name': 'CmpTraceManager:tracemgr_restart_packet',
  'component_id': 0x70},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555da54240, 0x55555da5436b],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/tracemgr_packet_reset.hex',
                     'instruction_indices': []}],
  'name': 'CmpTraceManager:tracemgr_packet_reset',
  'component_id': 0x70},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555da54380, 0x55555da547a9],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/tracemgr_recordadd.hex',
                     'instruction_indices': []}],
  'name': 'CmpTraceManager:tracemgr_recordadd',
  'component_id': 0x70},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555da547c0, 0x55555da54911],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/tracemgr_recordremove.hex',
                     'instruction_indices': []}],
  'name': 'CmpTraceManager:tracemgr_recordremove',
  'component_id': 0x70},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555da54940, 0x55555da54a9d],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/tracemgr_packetstore.hex',
                     'instruction_indices': []}],
  'name': 'CmpTraceManager:tracemgr_packetstore',
  'component_id': 0x70},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555da54ac0, 0x55555da54c28],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/tracemgr_packetrestore.hex',
                     'instruction_indices': []}],
  'name': 'CmpTraceManager:tracemgr_packetrestore',
  'component_id': 0x70},
 {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555da54c40, 0x55555da54f2e],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/tracemgr_loadconffromfile.hex',
                     'instruction_indices': []}],
  'name': 'CmpTraceManager:tracemgr_loadconffromfile',
  'component_id': 0x70},



  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555DA855C0, 0x55555DA85B65],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/SysEthernet_servicehandler.hex',
                     'instruction_indices': []}],
  'name': 'SysEthernet_servicehandler',
  'component_id': 0x11c},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555DA87BC0, 0x55555DA87BD7],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/SysEthernet_sub_1.hex',
                     'instruction_indices': []}],
  'name': 'SysEthernet_sub_1',
  'component_id': 0x11c},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555DA87C00, 0x55555DA87C0E],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/SysEthernet_sub_2.hex',
                     'instruction_indices': []}],
  'name': 'SysEthernet_sub_2',
  'component_id': 0x11c},


  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5CA400, 0x55555D5CA545],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_servicehandler.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_servicehandler',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5CA580, 0x55555D5CA628],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_1.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_1',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5BFC40, 0x55555D5BFD8F],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_2.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_2',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5CA180, 0x55555D5CA3D2],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_3.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_3',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C2740, 0x55555D5C28CE],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_4.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_4',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C5F00, 0x55555D5C62F9],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_5.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_5',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C5B00, 0x55555D5C5EDA],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_6.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_6',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C0A80, 0x55555D5C0C1B],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_7.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_7',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C1C80, 0x55555D5C20F4],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_8.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_8',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C0880, 0x55555D5C0A67],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_9.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_9',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C1A80, 0x55555D5C1C47],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_10.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_10',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C1800, 0x55555D5C1A76],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_11.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_11',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C0C40, 0x55555D5C0EA6],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_12.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_12',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C1440, 0x55555D5C17C4],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_13.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_13',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C3240, 0x55555D5C5AD9],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_14.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_14',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C0EC0, 0x55555D5C1187],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_15.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_15',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C2580, 0x55555D5C2718],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_16.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_16',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C2900, 0x55555D5C2E1C],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_17.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_17',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C3000, 0x55555D5C321B],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_18.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_18',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C2E40, 0x55555D5C2FD5],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_19.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_19',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C69C0, 0x55555D5CA15B],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_20.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_20',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C11C0, 0x55555D5CA15B],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_21.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_21',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C0400, 0x55555D5C0670],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_22.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_22',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C0780, 0x55555D5C0844],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_23.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_23',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5C0680, 0x55555D5C0753],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_24.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_24',
  'component_id': 0x02},
  {'coverage': 0,
  'memory_spaces': [{'address_range': [0x55555D5AF9C0, 0x55555D5AFAB9],
                     'covered_instructions': set(),
                     'data': '',
                     'input_file': 'hex/CmpApp_sub_25.hex',
                     'instruction_indices': []}],
  'name': 'CmpApp_sub_25',
  'component_id': 0x02},
  



]

